// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { NodeValue } from '../tree/node-value.js';


export class Channel {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Channel {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsChannel(bb:flatbuffers.ByteBuffer, obj?:Channel):Channel {
  return (obj || new Channel()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsChannel(bb:flatbuffers.ByteBuffer, obj?:Channel):Channel {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Channel()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value(obj?:NodeValue):NodeValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NodeValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

direction():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startChannel(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valueOffset, 0);
}

static addDirection(builder:flatbuffers.Builder, direction:boolean) {
  builder.addFieldInt8(1, +direction, +false);
}

static endChannel(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createChannel(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset, direction:boolean):flatbuffers.Offset {
  Channel.startChannel(builder);
  Channel.addValue(builder, valueOffset);
  Channel.addDirection(builder, direction);
  return Channel.endChannel(builder);
}
}
