// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { NodeValue } from '../tree/node-value.js';


export class Pointer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Pointer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPointer(bb:flatbuffers.ByteBuffer, obj?:Pointer):Pointer {
  return (obj || new Pointer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPointer(bb:flatbuffers.ByteBuffer, obj?:Pointer):Pointer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Pointer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value(obj?:NodeValue):NodeValue|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new NodeValue()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

reference():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startPointer(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valueOffset, 0);
}

static addReference(builder:flatbuffers.Builder, reference:boolean) {
  builder.addFieldInt8(1, +reference, +false);
}

static endPointer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPointer(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset, reference:boolean):flatbuffers.Offset {
  Pointer.startPointer(builder);
  Pointer.addValue(builder, valueOffset);
  Pointer.addReference(builder, reference);
  return Pointer.endPointer(builder);
}
}
