// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Type4 {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Type4 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsType4(bb:flatbuffers.ByteBuffer, obj?:Type4):Type4 {
  return (obj || new Type4()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsType4(bb:flatbuffers.ByteBuffer, obj?:Type4):Type4 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Type4()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startType4(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endType4(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createType4(builder:flatbuffers.Builder):flatbuffers.Offset {
  Type4.startType4(builder);
  return Type4.endType4(builder);
}
}
